version: "3.5"

services:

  client:
    container_name: client
    build: ./client
    user: 'node'
    working_dir: /home/node/app
    environment:
      - NODE_ENV=developer
    volumes:
      - ./client:/home/node/app
    ports:
      - '4200:42000'
    command: >
      /bin/sh -c 'npm i && npm start'

  server:
    container_name: server
    build: ./server
    user: 'node'
    working_dir: /home/node/app
    environment:
      - NODE_ENV=developer
    volumes:
      - ./server:/home/node/app
    ports:
      - '4201:42001'
    command: >
      /bin/sh -c 'npm i && npm start'
